server:
  port: 8080

spring:
  # 指定环境，决定选择配置文件
  profiles:
    active: dev
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: api-service-mock
          uri: lb://api-service-mock
          predicates:
            - Path=/api/mock/**
        - id: api-service-user
          uri: lb://api-service-user
          predicates:
            - Path=/api/user/**
        - id: api-service-api
          uri: lb://api-service-api
          predicates:
            - Path=/api/api/**
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: openapi3


